### ISSUE TITLE
echarts-ng2.module.ts is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by charlie447** [charlie447/ng-account#2]
After `ng serve`, the following error poped up:
echarts-ng2.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
```
ERROR in ./node_modules/echarts-ng2/src/component/echarts-ng2.module.ts
Module build failed: Error: /Users/czhang447/project/ng-account/node_modules/echarts-ng2/src/component/echarts-ng2.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/Users/czhang447/project/ng-account/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/Users/czhang447/project/ng-account/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by charlie447** [comment]
Putting the directory of `echarts-ng2.module.ts` file  to the 'include' property in the `tsconfig.app.json` . Like following:
`tsconfig.app.json`

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ],
  "include": [
    "../node_modules/echarts-ng2/src/component/echarts-ng2.component.ts",
    "../node_modules/echarts-ng2/src/component/echarts-ng2.module.ts",
    "./polyfills.ts",
    "./main.ts"
  ]
}
```
